package com.codechum.swing.jOptionPane;

import java.awt.*;
import java.awt.event.*;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class FindTheSpy extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form CODECHUMACTIVITY
     */
    public FindTheSpy() {
        initComponents();
        button1.addActionListener(this);
        button10.addActionListener(this);
        button2.addActionListener(this);
        button3.addActionListener(this);
        button4.addActionListener(this);
        button5.addActionListener(this);
        button6.addActionListener(this);
        button7.addActionListener(this);
        button8.addActionListener(this);
        button9.addActionListener(this);
    }
    
    public static boolean checkSpy(int input){
        int digit, sum = 0, product = 1;
        while (input > 0){
            digit = input % 10;
            sum += digit;
            product *= digit;
            input = input / 10;
        }
         
        return sum == product;
    }
    
    public void actionPerformed(ActionEvent e) {
        JButton button = (JButton) e.getSource();

        boolean isSpy = checkSpy(Integer.parseInt(button.getText()));
        
        if (isSpy) {
            JOptionPane.showMessageDialog(null, "Spy found!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Find the Spy");
        getContentPane().setLayout(new java.awt.FlowLayout());

        button1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button1.setText("2156");
        button1.setName("button1"); // NOI18N
        getContentPane().add(button1);

        button2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button2.setText("2265");
        button2.setName("button2"); // NOI18N
        getContentPane().add(button2);

        button3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button3.setText("124");
        button3.setName("button3"); // NOI18N
        getContentPane().add(button3);

        button4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button4.setText("2014");
        button4.setName("button4"); // NOI18N
        getContentPane().add(button4);

        button5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button5.setText("1214");
        button5.setName("button5"); // NOI18N
        getContentPane().add(button5);

        button6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button6.setText("562");
        button6.setName("button6"); // NOI18N
        getContentPane().add(button6);

        button7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button7.setText("11");
        button7.setName("button7"); // NOI18N
        getContentPane().add(button7);

        button8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button8.setText("22");
        button8.setName("button8"); // NOI18N
        getContentPane().add(button8);

        button9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button9.setText("213");
        button9.setName("button9"); // NOI18N
        getContentPane().add(button9);

        button10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button10.setText("54136");
        button10.setName("button10"); // NOI18N
        getContentPane().add(button10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindTheSpy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindTheSpy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindTheSpy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindTheSpy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindTheSpy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button10;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    // End of variables declaration//GEN-END:variables
}
