/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package customized;

import java.awt.event.WindowEvent;
import java.util.ArrayList;

/**
 *
 * @author AzalithenPC
 */
public class FoodServiceAWT extends java.awt.Frame {

    /**
     * Creates new form FoodServiceAWT
     */
    public FoodServiceAWT() {
        initComponents();

        // Solo P50, Medium 10inch P100, Large 12inch P150, Family 14inch P200
        list1.add("Solo P50");
        list1.add("Medium 10inch P100");
        list1.add("Large 12inch P150");
        list1.add("Family 14inch P200");

        // Thin P30, Thick P50, Stuffed P80, Hand-Tossed P100
        choice1.add("Thin P30");
        choice1.add("Thick P50");
        choice1.add("Stuffed P80");
        choice1.add("Hand-Tossed P100");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        label1 = new java.awt.Label();
        label3 = new java.awt.Label();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        checkbox3 = new java.awt.Checkbox();
        checkbox4 = new java.awt.Checkbox();
        checkbox5 = new java.awt.Checkbox();
        label4 = new java.awt.Label();
        list1 = new java.awt.List();
        label5 = new java.awt.Label();
        choice1 = new java.awt.Choice();
        button1 = new java.awt.Button();
        list2 = new java.awt.List();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();

        setTitle("Midterm Exam");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setName(""); // NOI18N
        label2.setText("Pick Your Choice");

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("FOOD SERVICE");

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setName(""); // NOI18N
        label3.setText("TOPPINGS");

        checkbox1.setLabel("Dine In");
        checkbox1.setName("dineInCheckbox"); // NOI18N
        checkbox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox1ItemStateChanged(evt);
            }
        });

        checkbox2.setLabel("Take Out");
        checkbox2.setName("takeOutCheckbox"); // NOI18N
        checkbox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox2ItemStateChanged(evt);
            }
        });

        checkbox3.setLabel("Sausage P40");
        checkbox3.setName("sausageCheckbox"); // NOI18N

        checkbox4.setLabel("Mushroom P30");
        checkbox4.setName("mushroomCheckbox"); // NOI18N

        checkbox5.setLabel("Pepperoni P50");
        checkbox5.setName("pepperoniCheckbox"); // NOI18N

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setName(""); // NOI18N
        label4.setText("SIZE");

        list1.setName("sizeList"); // NOI18N

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setName(""); // NOI18N
        label5.setText("CRUST");

        choice1.setName("crustChoice"); // NOI18N

        button1.setLabel("Place Order");
        button1.setName("placeOrderButton"); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        list2.setName("orderList"); // NOI18N

        button2.setLabel("Void");
        button2.setName("voidButton"); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setLabel("Proceed");
        button3.setName("proceedButton"); // NOI18N
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(checkbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkbox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkbox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void checkbox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox1ItemStateChanged
        // TODO add your handling code here:
        if (checkbox1.getState()) {
            checkbox2.setState(false);
        }
    }//GEN-LAST:event_checkbox1ItemStateChanged

    private void checkbox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox2ItemStateChanged
        // TODO add your handling code here:
        if (checkbox2.getState()) {
            checkbox1.setState(false);
        }
    }//GEN-LAST:event_checkbox2ItemStateChanged

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        
        list2.removeAll();
        int totalAmount = 0;

        String selectedFoodSerivce = checkbox1.getState() ? "Dine In" : "Take Out";

        ArrayList<String> selectedToppings = new ArrayList<>();
        if (checkbox3.getState()) {
            selectedToppings.add("Sausage P40");
            totalAmount += 40;
        }
        if (checkbox4.getState()) {
            selectedToppings.add("Mushroom P30");
            totalAmount += 30;
        }
        if (checkbox5.getState()) {
            selectedToppings.add("Pepperoni P50");
            totalAmount += 50;
        }

        String selectedSize = list1.getSelectedItem();
        String selectedCrust = choice1.getSelectedItem();

        if (selectedSize != null && selectedCrust != null) {
            totalAmount += Integer.parseInt(selectedSize.split("P")[1]);
            totalAmount += Integer.parseInt(selectedCrust.split("P")[1]);
        }

        list2.add(selectedFoodSerivce);
        selectedToppings.forEach((topping) -> {
            list2.add(topping);
        });
        list2.add(selectedSize);
        list2.add(selectedCrust);
        list2.add("\n");
        list2.add("Total Amount: P" + totalAmount);
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        list2.removeAll();

        checkbox1.setState(false);
        checkbox2.setState(false);
        checkbox3.setState(false);
        checkbox4.setState(false);
        checkbox5.setState(false);

        list1.deselect(list1.getSelectedIndex());
        choice1.select(0);

        // show dialog box with message "TRANSACTION VOIDED"
        java.awt.Dialog dialog = new java.awt.Dialog(this, "Message", true);
        dialog.setLayout(new java.awt.FlowLayout());
        dialog.add(new java.awt.Label("TRANSACTION VOIDED"));
        java.awt.Button button = new java.awt.Button("OK");

        button.addActionListener((java.awt.event.ActionEvent e) -> {
            dialog.dispose();
        });

        dialog.add(button);
        dialog.setSize(200, 100);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:

        // Extract the total amount from the last item in the list
        String totalAmount = list2.getItem(list2.getItemCount() - 1).split("P")[1];

        // Setup the Dialog for user input
        java.awt.Dialog inputDialog = new java.awt.Dialog(this, "Input", true);
        inputDialog.setLayout(new java.awt.GridLayout(4, 1)); // Adjusting grid layout to separate elements more clearly

        // Create components
        java.awt.Label promptLabel = new java.awt.Label("Total " + totalAmount);
        java.awt.Label inputLabel = new java.awt.Label("Enter Cash:");
        java.awt.TextField inputField = new java.awt.TextField();

        // Panel for buttons
        java.awt.Panel buttonPanel = new java.awt.Panel();
        buttonPanel.setLayout(new java.awt.FlowLayout());
        java.awt.Button okButton = new java.awt.Button("OK");
        java.awt.Button cancelButton = new java.awt.Button("Cancel");

        // Add components to the dialog in the correct order
        inputDialog.add(promptLabel);
        inputDialog.add(inputLabel);
        inputDialog.add(inputField);
        buttonPanel.add(okButton);
        buttonPanel.add(cancelButton);
        inputDialog.add(buttonPanel);

        // Action listeners for buttons
        okButton.addActionListener(e -> {
            inputDialog.setVisible(false);
            String cash = inputField.getText();
            if (!cash.isEmpty()) {
                try {
                    int change = Integer.parseInt(cash) - Integer.parseInt(totalAmount);
                    if (change < 0) {
                        showDialog("INSUFFICIENT CASH", "Error");
                    } else {
                        showDialog("Change: " + change, "Message");
                    }
                } catch (NumberFormatException nfe) {
                    showDialog("Invalid cash amount entered", "Error");
                }
            }
        });

        cancelButton.addActionListener(e -> inputDialog.setVisible(false));

        // Dialog sizing and visibility
        inputDialog.setSize(300, 150);
        inputDialog.setLocationRelativeTo(this);
        inputDialog.setVisible(true);

    }//GEN-LAST:event_button3ActionPerformed

    private void showDialog(String message, String title) {
        java.awt.Dialog messageDialog = new java.awt.Dialog(this, title, true);
        messageDialog.setLayout(new java.awt.FlowLayout());
        messageDialog.add(new java.awt.Label(message));
        java.awt.Button ok = new java.awt.Button("OK");
        ok.addActionListener(e -> messageDialog.setVisible(false));
        messageDialog.add(ok);
        messageDialog.setSize(200, 100);
        messageDialog.setLocationRelativeTo(this);
        messageDialog.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodServiceAWT().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox2;
    private java.awt.Checkbox checkbox3;
    private java.awt.Checkbox checkbox4;
    private java.awt.Checkbox checkbox5;
    private java.awt.Choice choice1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.List list1;
    private java.awt.List list2;
    // End of variables declaration//GEN-END:variables
}
