package com.codechum.swing.jCheckBox;

public class SelectingCheckBoxes extends javax.swing.JFrame {

    /**
     * Creates new form CODECHUMACTIVITY
     */
    public SelectingCheckBoxes() {
        initComponents();
        this.setTitle("CheckBoxes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstCheckBox = new javax.swing.JCheckBox();
        secondCheckBox = new javax.swing.JCheckBox();
        thirdCheckBox = new javax.swing.JCheckBox();
        displaySelectedButton = new javax.swing.JButton();
        checkBoxesLabel = new javax.swing.JLabel();

        firstCheckBox.setName("firstCheckBox");
        secondCheckBox.setName("secondCheckBox");
        thirdCheckBox.setName("thirdCheckBox");
        displaySelectedButton.setName("displaySelectedButton");
        checkBoxesLabel.setName("checkBoxesLabel");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstCheckBox.setText("First");

        secondCheckBox.setText("Second");

        thirdCheckBox.setText("Third");

        displaySelectedButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        displaySelectedButton.setText("Display");
        displaySelectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayTextActionPerformed(evt);
            }
        });

        checkBoxesLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkBoxesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thirdCheckBox)
                            .addComponent(secondCheckBox)
                            .addComponent(firstCheckBox)
                            .addComponent(checkBoxesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(displaySelectedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(firstCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thirdCheckBox)
                .addGap(18, 18, 18)
                .addComponent(displaySelectedButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisplayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayTextActionPerformed
        // TODO add your handling code here:
        String display = "";
        
        if (firstCheckBox.isSelected()) {
            display += "First";
        }
        
        if (secondCheckBox.isSelected()) {
            if (display.length() > 0) {
                display += ", Second";
            }
            else {
                display += "Second";
            }
        }
        
        if (thirdCheckBox.isSelected()) {
            if (display.length() > 0) {
                display += ", Third";
            }
            else {
                display += "Third";
            }
        }
        
        checkBoxesLabel.setText(display);
    }//GEN-LAST:event_btnDisplayTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectingCheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectingCheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectingCheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectingCheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectingCheckBoxes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton displaySelectedButton;
    private javax.swing.JCheckBox firstCheckBox;
    private javax.swing.JCheckBox secondCheckBox;
    private javax.swing.JCheckBox thirdCheckBox;
    private javax.swing.JLabel checkBoxesLabel;
    // End of variables declaration//GEN-END:variables
}
