package com.codechum.awt.dialog;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FindTheSpy extends java.awt.Frame implements ActionListener {

    /**
     * Creates new form CODECHUMACTIVITY
     */
    public FindTheSpy() {
        initComponents();
        dialogNotice = new Dialog(this, "Message", false);
        dialogNotice.setSize(200, 200);
        Label lblMessage = new Label("Spy found!");
        lblMessage.setName("lblMessage");
        Panel leapYearPanel = new Panel(new BorderLayout());
        leapYearPanel.add(new Panel(), BorderLayout.NORTH);
        leapYearPanel.add(new Panel(), BorderLayout.SOUTH);
        leapYearPanel.add(lblMessage, BorderLayout.CENTER);
        leapYearPanel.add(new Panel(), BorderLayout.EAST);
        leapYearPanel.add(new Panel(), BorderLayout.WEST);
        dialogNotice.add(leapYearPanel);
        dialogNotice.setName("dialogNotice");
        dialogNotice.setVisible(false);
        
        button1.addActionListener(this);
        button11.addActionListener(this);
        button2.addActionListener(this);
        button3.addActionListener(this);
        button4.addActionListener(this);
        button7.addActionListener(this);
        button6.addActionListener(this);
        button8.addActionListener(this);
        button9.addActionListener(this);
        button10.addActionListener(this);
        
        button1.setName("button1");
        button11.setName("button10");
        button2.setName("button2");
        button3.setName("button3");
        button4.setName("button4");
        button6.setName("button5");
        button7.setName("button6");
        button8.setName("button7");
        button9.setName("button8");
        button10.setName("button9");
    }
    
    public static boolean checkSpy(int input){
        int digit, sum = 0, product = 1;
        while (input > 0){
            digit = input % 10;
            sum += digit;
            product *= digit;
            input = input / 10;
        }
         
        return sum == product;
    }
    
    public void actionPerformed(ActionEvent e) {
        Button button = (Button) e.getSource();

        boolean isSpy = checkSpy(Integer.parseInt(button.getLabel()));
        
        if (isSpy) {
            dialogNotice.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        button10 = new java.awt.Button();
        button11 = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new java.awt.FlowLayout());

        button1.setLabel("2156");
        button1.setName("button1"); // NOI18N
        add(button1);

        button2.setLabel("2265");
        button2.setName("button2"); // NOI18N
        add(button2);

        button3.setLabel("124");
        button3.setName("button3"); // NOI18N
        add(button3);

        button4.setLabel("2014");
        button4.setName("button4"); // NOI18N
        add(button4);

        button6.setLabel("1214");
        button6.setName("button5"); // NOI18N
        add(button6);

        button7.setLabel("562");
        button7.setName("button6"); // NOI18N
        add(button7);

        button8.setLabel("11");
        button8.setName("button7"); // NOI18N
        add(button8);

        button9.setLabel("22");
        button9.setName("button8"); // NOI18N
        add(button9);

        button10.setLabel("213");
        button10.setName("button9"); // NOI18N
        add(button10);

        button11.setLabel("54136");
        button11.setName("button10"); // NOI18N
        add(button11);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindTheSpy().setVisible(true);
            }
        });
    }

    private java.awt.Dialog dialogNotice;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    // End of variables declaration//GEN-END:variables
}
