/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.codechum.awt.eventClasses;

/**
 *
 * @author alysa
 */
public class ActionEventActivity extends java.awt.Frame {

    /**
     * Creates new form AWTActionEvent1
     */
    public ActionEventActivity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        label1 = new java.awt.Label();

        setTitle("Text Color Changer");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setLabel("Color Change");
        button1.setName("colorChangeButton"); // NOI18N
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        button1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                button1ComponentResized(evt);
            }
        });
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setName("textLabel"); // NOI18N
        label1.setText("HELLO WORLD");
        label1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                label1ComponentResized(evt);
            }
        });
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_button1ComponentResized
            
    }//GEN-LAST:event_button1ComponentResized

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        if (label1.getForeground() == java.awt.Color.red) {
            label1.setForeground(java.awt.Color.blue);
        } else if (label1.getForeground() == java.awt.Color.blue) {
            label1.setForeground(java.awt.Color.green);
        } else {
            label1.setForeground(java.awt.Color.red);
        }  
    }//GEN-LAST:event_button1ActionPerformed

    private void label1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_label1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_label1ComponentResized

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
        // Change the color of the label alternating between red, blue and green
        
    }//GEN-LAST:event_button1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActionEventActivity().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
