package com.codechum.awt.labels;

public class LovingJava extends java.awt.Frame {

    /**
     * Creates new form NewFrame
     */
    public LovingJava() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();

        setMinimumSize(new java.awt.Dimension(410, 250));
        setTitle("My First App");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setName("label1"); // NOI18N
        label1.setText("Hello World!");
        add(label1);
        label1.setBounds(140, 60, 120, 30);

        label2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label2.setName("label2"); // NOI18N
        label2.setText("I love programming");
        add(label2);
        label2.setBounds(120, 100, 170, 30);

        label3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label3.setName("label3"); // NOI18N
        label3.setText("I love CodeChum");
        add(label3);
        label3.setBounds(130, 140, 170, 30);

        label4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label4.setName("label4"); // NOI18N
        label4.setText("I love Java");
        add(label4);
        label4.setBounds(150, 180, 170, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LovingJava().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
}
