/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.codechum.awt.labels;

/**
 *
 * @author AzalithenPC
 */
public class ThreeColumns extends java.awt.Frame {

    /**
     * Creates new form CODECHUMACTIVITY
     */
    public ThreeColumns() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();

        setTitle("Three Columns");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new java.awt.GridLayout(1, 0));

        label1.setName("label1");
        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(java.awt.Color.lightGray);
        label1.setName("label1"); // NOI18N
        label1.setText("This is the first column");
        add(label1);
        label1.getAccessibleContext().setAccessibleDescription("");

        label2.setName("label2");
        label2.setAlignment(java.awt.Label.CENTER);
        label2.setName("label2"); // NOI18N
        label2.setText("This is the second column");
        add(label2);

        label3.setName("label3");
        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(java.awt.Color.lightGray);
        label3.setName("label3"); // NOI18N
        label3.setText("This is the third column");
        add(label3);

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThreeColumns().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
