/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.codechum.awt.graphicsClass;

import java.awt.Canvas;
import java.awt.Graphics;

/**
 *
 * @author alysa
 */
public class DrawingACircle extends java.awt.Frame {

    /**
     * Creates new form AWTGraphics1
     */
    public DrawingACircle() {
        initComponents();
        setSize(400, 400);
        setLocationRelativeTo(null);
    }
    
    @Override
    public void paint(Graphics g){
        int centerX = getWidth() / 2;
        int centerY = getHeight() / 2;
        int radius = 50;

        g.drawOval(centerX - radius, centerY - radius, 2 * radius, 2 * radius);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTitle("Drawing a Circle");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawingACircle().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
