/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.codechum.awt.textArea;

/**
 *
 * @author AzalithenPC
 */
public class CharacterCounter extends java.awt.Frame {

    /**
     * Creates new form AWTTextArea1
     */
    public CharacterCounter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        button1 = new java.awt.Button();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();

        setTitle("Character Counter");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textArea1.setName("messageTextArea"); // NOI18N
        add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 350, 230));

        label1.setName("label1"); // NOI18N
        label1.setText("Enter character: ");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 90, -1));

        textField1.setName("characterTextField"); // NOI18N
        add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 50, -1));

        button1.setLabel("Count");
        button1.setName("countButton"); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        label2.setName("label2"); // NOI18N
        label2.setText("Count: ");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setName("countLabel"); // NOI18N
        label3.setText("0");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        char find = textField1.getText().charAt(0);
        int count = 0;
        String message = textArea1.getText();
        
        for (int i = 0; i < message.length(); i++) {
            if (message.charAt(i) == find) {
                count++;
            }
        }
        
        label3.setText(count + "");
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterCounter().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextArea textArea1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
