package com.codechum.awt.menu;

import java.awt.Color;
import java.awt.MenuItem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MenuInAMenu extends java.awt.Frame implements ActionListener {

    /**
     * Creates new form AWTMenu
     */
    public MenuInAMenu() {
        initComponents();
        MenuItem mnuNew = new MenuItem("New");
        MenuItem mnuOpen = new MenuItem("Open");
        MenuItem mnuSave = new MenuItem("Save");
        MenuItem mnuExit = new MenuItem("Exit");
        MenuItem mnuRed = new MenuItem("Red");
        MenuItem mnuGreen = new MenuItem("Green");
        MenuItem mnuBlue = new MenuItem("Blue");

        mnuNew.setName("newMenuItem");
        mnuOpen.setName("openMenuItem");
        mnuSave.setName("saveMenuItem");
        mnuExit.setName("exitMenuItem");
        mnuRed.setName("redColorMenuItem");
        mnuGreen.setName("greenColorMenuItem");
        mnuBlue.setName("blueColorMenuItem");

        fileMenu.add(mnuNew);
        fileMenu.add(mnuOpen);
        fileMenu.add(mnuSave);
        fileMenu.addSeparator();
        fileMenu.add(mnuExit);

        fontColorMenu.add(mnuRed);
        fontColorMenu.add(mnuGreen);
        fontColorMenu.add(mnuBlue);

        mnuNew.addActionListener(this);
        mnuOpen.addActionListener(this);
        mnuSave.addActionListener(this);
        mnuExit.addActionListener(this);
        mnuRed.addActionListener(this);
        mnuGreen.addActionListener(this);
        mnuBlue.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        statusLabel = new java.awt.Label();
        menuBar1 = new java.awt.MenuBar();
        fileMenu = new java.awt.Menu();
        formatMenu = new java.awt.Menu();
        fontColorMenu = new java.awt.Menu();

        jMenuItem1.setText("jMenuItem1");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        statusLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        statusLabel.setName("statusLabel"); // NOI18N

        menuBar1.setName("menuBar");

        fileMenu.setLabel("File");
        fileMenu.setName("fileMenu");
        menuBar1.add(fileMenu);

        formatMenu.setLabel("Format");
        formatMenu.setName("formatMenu");

        fontColorMenu.setLabel("Font Color");
        fontColorMenu.setName("fontColorMenu");
        formatMenu.add(fontColorMenu);

        menuBar1.add(formatMenu);

        setMenuBar(menuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(130, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(101, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_exitForm
        System.exit(0);
    }// GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInAMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private java.awt.Label statusLabel;
    private java.awt.Menu fileMenu;
    private java.awt.Menu formatMenu;
    private java.awt.Menu fontColorMenu;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        MenuItem menu = (MenuItem) e.getSource();

        if (menu.getName().equals("newMenuItem")) {
            statusLabel.setText("Creating new file...");
        } else if (menu.getName().equals("openMenuItem")) {
            statusLabel.setText("Opening file...");
        } else if (menu.getName().equals("saveMenuItem")) {
            statusLabel.setText("Saving file...");
        } else if (menu.getName().equals("redColorMenuItem")) {
            statusLabel.setForeground(Color.RED);
        } else if (menu.getName().equals("greenColorMenuItem")) {
            statusLabel.setForeground(Color.GREEN);
        } else if (menu.getName().equals("blueColorMenuItem")) {
            statusLabel.setForeground(Color.BLUE);
        } else {
            this.dispose();
        }
    }
}
