/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */

package com.codechum.awt.list;

/**
 *
 * @author AzalithenPC
 */
public class MyPlaylistButWithFavorites extends java.awt.Frame {

    /** Creates new form MyPlaylistButWithFavorites */
    public MyPlaylistButWithFavorites() {
        initComponents();

        musicList.add("Music Main 1");
        musicList.add("Music Main 2");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        favoritesList = new java.awt.List();
        musicList = new java.awt.List();
        addToFavoritesButton = new java.awt.Button();
        textField1 = new java.awt.TextField();
        label1 = new java.awt.Label();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();

        setTitle("Music Player");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        favoritesList.setName("favoritesList"); // NOI18N
        add(favoritesList, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 190, 180));

        musicList.setName("musicList"); // NOI18N
        add(musicList, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 190, 180));

        addToFavoritesButton.setLabel(">");
        addToFavoritesButton.setName("addToFavoritesButton"); // NOI18N
        addToFavoritesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToFavoritesButtonActionPerformed(evt);
            }
        });
        add(addToFavoritesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 50, 70));

        textField1.setName("musicTextField"); // NOI18N
        add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 260, 30));

        label1.setName(""); // NOI18N
        label1.setText("Title:");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 40, 30));

        button2.setLabel("Remove");
        button2.setName("removeButton"); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 120, 40));

        button3.setLabel("Add");
        button3.setName("addButton"); // NOI18N
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 120, 40));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setText("Music List");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 70, -1));

        label3.setName(""); // NOI18N
        label3.setText("Favorites");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void addToFavoritesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToFavoritesButtonActionPerformed
        // TODO add your handling code here:
        String name = musicList.getSelectedItem();
        
        if (name != null) {
            String[] favorites = favoritesList.getItems();

            boolean isAlreadyInFavorites = false;

            for (String favorite : favorites) {
                if (favorite.equals(name)) {
                    isAlreadyInFavorites = true;
                    break;
                }
            }

            if (!isAlreadyInFavorites) {
                favoritesList.add(name);
            }
        }
       
    }//GEN-LAST:event_addToFavoritesButtonActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        String name = textField1.getText();

        if (name != null) {
            musicList.add(name);
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        // Can only remove in musicList
        String name = musicList.getSelectedItem();

        if (name != null) {
            musicList.remove(name);
            // Remove from favoritesList
            favoritesList.remove(name);
        }
    }//GEN-LAST:event_button2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyPlaylistButWithFavorites().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button addToFavoritesButton;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.List favoritesList;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.List musicList;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables

}
