/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.codechum.awt.fileDialog;

import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alysa
 */
public class FileMerger extends java.awt.Frame {

    /**
     * Creates new form FileMerger
     */
    
    private StringBuilder mergedText = new StringBuilder();
    
    public FileMerger() {
        initComponents();
        fd = new FileDialog(this, "Save Files", FileDialog.LOAD);
        fd.setName("fileDialog");
        setTitle("File Merger");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        button1 = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textField1.setName("contentTextField"); // NOI18N
        add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 290, 120));

        button1.setLabel("Open");
        button1.setName("openFileButton"); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        fd.setMultipleMode(true); // Allow multiple file selection
        fd.setVisible(true);

        File[] selectedFiles = fd.getFiles();

        if (selectedFiles.length > 0) {
            for (File inputFile : selectedFiles) {
                try (InputStream is = new FileInputStream(inputFile);
                    BufferedReader br = new BufferedReader(new InputStreamReader(is))) {

                    String str;
                    while ((str = br.readLine()) != null) {
                        mergedText.append(str).append(System.lineSeparator());
                    }

                } catch (FileNotFoundException ex) {
                    Logger.getLogger(FileMerger.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(FileMerger.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            textField1.setText(mergedText.toString().trim());
        }
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileMerger().setVisible(true);
            }
        });
    }

    private java.awt.FileDialog fd;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
