package com.codechum.awt.fileDialog;

import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;

public class MakingAMessage extends java.awt.Frame {

    /**
     * Creates new form CODECHUMACTIVITY
     */
    public MakingAMessage() {
        initComponents();
        fd = new FileDialog(this, "Save Files", FileDialog.SAVE);
        fd.setName("fileDialog");
        setTitle("File Saver");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileContentLabel = new java.awt.Label();
        createFileButton = new java.awt.Button();
        label2 = new java.awt.Label();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        fileContentLabel.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        fileContentLabel.setName("fileContentLabel"); // NOI18N

        createFileButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        createFileButton.setLabel("Create File");
        createFileButton.setName("createFileButton"); // NOI18N
        createFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label2.setName(""); // NOI18N
        label2.setText("Content of the created file");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(createFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(fileContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(fileContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(createFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        fd.setVisible(true);
        
        File oneFile = new File(fd.getFile());
        try {
            oneFile.createNewFile();
        } catch (IOException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
        
        FileWriter myWriter;
        try {
            myWriter = new FileWriter(fd.getFile());
            myWriter.write("File handling");
            myWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(MakingAMessage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        File inputFile = new File(fd.getFile());
        InputStream is;
        try {
            is = new FileInputStream(inputFile);
            BufferedReader br = new BufferedReader(new InputStreamReader(is));
            String str = "";
            String text = "";
            while ((str = br.readLine()) != null) {
                text += str;
            }
            
            fileContentLabel.setText(text);
            is.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MakingAMessage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MakingAMessage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakingAMessage().setVisible(true);
            }
        });
    }


    private java.awt.FileDialog fd;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button createFileButton;
    private java.awt.Label fileContentLabel;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
