/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.codechum.awt.choice;

/**
 *
 * @author AzalithenPC
 */
public class FishPriceOfTheDay extends java.awt.Frame {

    /**
     * Creates new form AWTChoice1
     */
    public FishPriceOfTheDay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        textField1 = new java.awt.TextField();
        button1 = new java.awt.Button();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();

        setTitle("Fish Price of the Day");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        choice1.setName("dayChoice"); // NOI18N
        choice1.add("Monday");
        choice1.add("Tuesday");
        choice1.add("Wednesday");
        choice1.add("Thursday");
        choice1.add("Friday");
        choice1.add("Saturday");
        choice1.add("Sunday");
        choice1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choice1ItemStateChanged(evt);
            }
        });
        add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 320, 60));

        textField1.setName("amountTextField"); // NOI18N
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 120, -1));

        button1.setLabel("Calculate");
        button1.setName("calculateButton"); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 100, -1));

        label1.setName("label1"); // NOI18N
        label1.setText("Price:");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        label2.setName("priceLabel"); // NOI18N
        label2.setText("0");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 120, -1));

        label3.setName(""); // NOI18N
        label3.setText("Amount");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        String choice = choice1.getSelectedItem();
        int amount = Integer.valueOf(textField1.getText());
        int price;

        switch (choice) {
            case "Monday":
                price = 250;
                break;
            case "Tuesday":
                price = 200;
                break;
            case "Wednesday":
            case "Thursday":
                price = 150;
                break;
            case "Friday":
                price = 200;
                break;
            case "Saturday":
            case "Sunday":
                price = 300;
                break;
            default:
                price = 0; // Default case if none of the days match
                break;
        }
        
        label2.setText(String.valueOf(price * amount));
    }//GEN-LAST:event_button1ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void choice1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choice1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_choice1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FishPriceOfTheDay().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Choice choice1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
