/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.codechum.awt.choice;

/**
 *
 * @author USER
 */
public class PizzaOrderSystem extends java.awt.Frame {

    /**
     * Creates new form AWTChoice2
     */
    public PizzaOrderSystem() {
        initComponents();
        choice1.add("Small");
        choice1.add("Medium");
        choice1.add("Large");
        
        choice2.add("Pepperoni");
        choice2.add("Mushrooms");
        choice2.add("Onions");

        choice3.add("Yes");
        choice3.add("No");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        choice2 = new java.awt.Choice();
        choice3 = new java.awt.Choice();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        button1 = new java.awt.Button();
        label4 = new java.awt.Label();

        setTitle("Pizza Order System");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        choice1.setName("pizzaSizeCheckBox"); // NOI18N
        add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 190, -1));

        choice2.setName("pizzaTopppingsCheckBox"); // NOI18N
        add(choice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 190, -1));

        choice3.setName("extraCheeseCheckBox"); // NOI18N
        add(choice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 190, -1));

        label1.setText("Size:");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        label2.setText("Toppings:");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        label3.setText("Extra Cheese:");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        button1.setLabel("Calculate Total");
        button1.setName("calculateButton"); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        label4.setName("totalLabel"); // NOI18N
        label4.setText("0");
        add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        int basePrice = 0;

        String size = choice1.getSelectedItem();
         
            switch (size) {
                case "Small":
                    basePrice = 10;
                    break;
                case "Medium":
                    basePrice = 15;
                    break;
                case "Large":
                    basePrice = 20;
                    break;
            }
        
        // Add $2 for each selected topping
        int toppingsPrice = 0;
        
        if (choice2.getSelectedItem() != null) {
            toppingsPrice += 2;
        }

        // Add $3 for extra cheese if selected
        int extraCheesePrice = "Yes".equals(choice3.getSelectedItem()) ? 3 : 0;

        // Calculate total price
        int totalPrice = basePrice + toppingsPrice + extraCheesePrice;

        // Display the result in the label
        label4.setText(String.valueOf(totalPrice));
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaOrderSystem().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Choice choice1;
    private java.awt.Choice choice2;
    private java.awt.Choice choice3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
}
