/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.codechum.awt.checkBoxGroup;

/**
 *
 * @author alysa
 */

import java.awt.*;

public class CheckboxGroupSurvey extends java.awt.Frame {

    /**
     * Creates new form AWTCheckGroup2
     */

    private CheckboxGroup genderGroup, languageGroup;
    private Checkbox maleCheckbox, femaleCheckbox, javaCheckbox, pythonCheckbox, cppCheckbox, csharpCheckbox, javascriptCheckbox;
    private Label resultLabel;
    private Button submitButton;

    public CheckboxGroupSurvey() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setTitle("CheckboxGroup Survey");
        setLayout(new BorderLayout(10, 10));

        genderGroup = new CheckboxGroup();
        languageGroup = new CheckboxGroup();

        maleCheckbox = new Checkbox("Male", genderGroup, false);
        femaleCheckbox = new Checkbox("Female", genderGroup, false);

        javaCheckbox = new Checkbox("Java", languageGroup, false);
        pythonCheckbox = new Checkbox("Python", languageGroup, false);
        cppCheckbox = new Checkbox("C++", languageGroup, false);
        csharpCheckbox = new Checkbox("C#", languageGroup, false);
        javascriptCheckbox = new Checkbox("JavaScript", languageGroup, false);

        resultLabel = new Label();
        resultLabel.setName("resultLabel");

        submitButton = new Button("Submit");
        submitButton.setName("submitButton");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                submitResponse();
            }
        });

        // Set the names of the components
        maleCheckbox.setName("maleCheckbox");
        femaleCheckbox.setName("femaleCheckbox");
        javaCheckbox.setName("javaCheckbox");
        pythonCheckbox.setName("pythonCheckbox");
        cppCheckbox.setName("cppCheckbox");
        csharpCheckbox.setName("csharpCheckbox");
        javascriptCheckbox.setName("javascriptCheckbox");

        Panel checkboxesPanel = new Panel(new GridLayout(0, 1, 0, 5));
        checkboxesPanel.add(new Label("Gender:"));
        checkboxesPanel.add(maleCheckbox);
        checkboxesPanel.add(femaleCheckbox);

        Panel languagesPanel = new Panel(new GridLayout(0, 1, 0, 5));
        languagesPanel.add(new Label("Programming Languages:"));
        languagesPanel.add(javaCheckbox);
        languagesPanel.add(pythonCheckbox);
        languagesPanel.add(cppCheckbox);
        languagesPanel.add(csharpCheckbox);
        languagesPanel.add(javascriptCheckbox);

        Panel leftPanel = new Panel(new BorderLayout(10, 10));
        leftPanel.add(checkboxesPanel, BorderLayout.WEST);

        Panel rightPanel = new Panel(new BorderLayout(10, 10));
        rightPanel.add(languagesPanel, BorderLayout.WEST);

        Panel centerPanel = new Panel(new BorderLayout(10, 10));
        centerPanel.add(leftPanel, BorderLayout.WEST);
        centerPanel.add(rightPanel, BorderLayout.EAST);

        Panel bottomPanel = new Panel(new BorderLayout());
        bottomPanel.add(submitButton, BorderLayout.CENTER);
        bottomPanel.add(resultLabel, BorderLayout.SOUTH);

        add(centerPanel, BorderLayout.CENTER);
        add(bottomPanel, BorderLayout.SOUTH);

        setSize(300, 200);
        setVisible(true);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void submitResponse() {
        resultLabel.setText("Your response has been recorded.");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckboxGroupSurvey().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
