/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.codechum.awt.checkBoxGroup;

/**
 *
 * @author alysa
 */

import java.awt.*;
import java.awt.event.*;

public class DynamicCheckbox extends java.awt.Frame {

    /**
     * Creates new form AWTCheckboxGroup1
     */

    private CheckboxGroup checkboxGroup;
    private Checkbox checkbox1, checkbox2;
    private Choice categoryComboBox;

    public DynamicCheckbox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setTitle("Dynamic Checkbox");
        setLayout(new FlowLayout());

        checkboxGroup = new CheckboxGroup();

        checkbox1 = new Checkbox("Pizza", checkboxGroup, false);
        checkbox2 = new Checkbox("Coke", checkboxGroup, false);

        categoryComboBox = new Choice();
        categoryComboBox.add("Food");
        categoryComboBox.add("Drinks");

        categoryComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateCheckboxes();
            }
        });

        add(categoryComboBox);
        add(checkbox1);
        add(checkbox2);

        // Name the components
        checkbox1.setName("checkbox1");
        checkbox2.setName("checkbox2");
        categoryComboBox.setName("categoryComboBox");

        updateCheckboxes();  // Initialize checkboxes based on default selection

        setSize(300, 150);
        setVisible(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void updateCheckboxes() {
        String selectedCategory = categoryComboBox.getSelectedItem();
        checkbox1.setLabel(selectedCategory.equals("Food") ? "Pizza" : "Coke");
        checkbox2.setLabel(selectedCategory.equals("Food") ? "Burger" : "Orange Juice");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DynamicCheckbox().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
