package com.codechum.awt.checkBoxGroup;

import java.util.ArrayList;
import java.util.List;

import java.awt.*;

public class ReceiptGenerator extends javax.swing.JFrame {

    /**
     * Creates new form CODECHUMACTIVITY
     */
    public ReceiptGenerator() {
        initComponents();
        setTitle("Receipt Generator");
        cmbPaymentMethod.setName("paymentMethodChoice");
        txtName.setName("nameTextField");
        txaReceipt.setName("receiptTextArea");
        chkShoes.setName("shoesCheckBox");
        chkPants.setName("pantsCheckBox");
        chkShirt.setName("shirtCheckBox");
        btnGenerate.setName("generateButton");
        radDefault.setName("defaultCheckBox");
        radSpecial.setName("specialCheckBox");

        txaReceipt.setEditable(false);

        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        this.setSize(800, 450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        promosCheckBoxGroup = new CheckboxGroup();
        jLabel1 = new Label();
        cmbPaymentMethod = new Choice();
        jLabel2 = new Label();
        jLabel3 = new Label();
        txtName = new TextField();
        jLabel4 = new Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaReceipt = new TextArea();
        chkShoes = new Checkbox();
        chkPants = new Checkbox();
        chkShirt = new Checkbox();
        btnGenerate = new Button();
        radDefault = new Checkbox("Default", promosCheckBoxGroup, true);
        radSpecial = new Checkbox("Special", promosCheckBoxGroup, false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Payment Method");

        cmbPaymentMethod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbPaymentMethod.add("Cash");
        cmbPaymentMethod.add("Credit Card");
        cmbPaymentMethod.add("Debit Card");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Items");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Name");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Promos");

        txaReceipt.setColumns(20);
        txaReceipt.setRows(5);
        jScrollPane1.setViewportView(txaReceipt);

        chkShoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkShoes.setLabel("Shoes  -    P 200");

        chkPants.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkPants.setLabel("Pants   -    P 150");

        chkShirt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkShirt.setLabel("Shirt    -    P 120");

        btnGenerate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGenerate.setLabel("Generate Receipt");

        radDefault.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        radSpecial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkShoes)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkPants)
                            .addComponent(chkShirt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnGenerate)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(radSpecial, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkShoes)
                    .addComponent(radDefault))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPants)
                    .addComponent(radSpecial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkShirt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String receipt = "Name: " + txtName.getText() + "\nItems: ";
        List<String> items = new ArrayList<String>();
        double totalPrice = 0;

        if(chkShoes.getState()) {
            totalPrice += 200;
            items.add("Shoes");
        }
        if(chkPants.getState()) {
            totalPrice += 150;
            items.add("Pants");
        }
        if(chkShirt.getState()) {
            totalPrice += 120;
            items.add("Shirt");
        }

        for(int i = 0; i < items.size(); i++) {
            if (i == items.size() - 1) {
                receipt += items.get(i);
            } else {
                receipt += items.get(i) + ", ";
            }
        }

        receipt += "\nPayment Method: ";
        if(cmbPaymentMethod.getSelectedItem().equals(cmbPaymentMethod.getItem(0))){
            receipt += "Cash";
        }
        else if(cmbPaymentMethod.getSelectedItem().equals(cmbPaymentMethod.getItem(1))){
            receipt += "Credit Card";
        }
        else if(cmbPaymentMethod.getSelectedItem().equals(cmbPaymentMethod.getItem(2))){
            receipt += "Debit Card";
        }

        if(radDefault.getState()) {
            if (totalPrice >= 300) {
                totalPrice = totalPrice - (totalPrice * 0.05);
            }
        }

        if(radSpecial.getState()) {
            totalPrice = totalPrice - (totalPrice * 0.15);
        }

        receipt += "\nTotal Cost: " + Double.toString(totalPrice) + 0;
        txaReceipt.setText(receipt);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiptGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiptGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiptGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiptGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceiptGenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CheckboxGroup promosCheckBoxGroup;
    private Button btnGenerate;
    private Checkbox chkPants;
    private Checkbox chkShirt;
    private Checkbox chkShoes;
    private Choice cmbPaymentMethod;
    private Label jLabel1;
    private Label jLabel2;
    private Label jLabel3;
    private Label jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private Checkbox radDefault;
    private Checkbox radSpecial;
    private TextArea txaReceipt;
    private TextField txtName;
    // End of variables declaration//GEN-END:variables
}