/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.codechum.awt.colorClass;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author alysa
 */
public class ShapeInAShape extends java.awt.Frame {

    /**
     * Creates new form AWTColorClass2
     */
    public ShapeInAShape() {
        initComponents();
        setTitle("Shape in a Shape");
        setSize(400, 400);
        setLocationRelativeTo(null);
    }
    
    @Override
    public void paint(Graphics g) {
        int centerX = 200;
        int centerY = 200;
        int circleRadius = 150;
        int rectangleWidth = 150;
        int rectangleHeight = 50;

        // Draw red circle
        g.setColor(Color.RED);
        g.fillOval(centerX - circleRadius, centerY - circleRadius, 2 * circleRadius, 2 * circleRadius);

        // Draw white rectangle inside the circle
        g.setColor(Color.WHITE);
        g.fillRect(centerX - rectangleWidth / 2, centerY - rectangleHeight / 2, rectangleWidth, rectangleHeight);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShapeInAShape().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
