package com.codechum.awt.drawingShapes;

import java.awt.*;

public class DrawingArcs extends java.awt.Frame {

    /**
     * Creates new form CODECHUMACTIVITY
     */
    public DrawingArcs() {
        initComponents();
        setTitle("Arcs");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainCanvas = new java.awt.Canvas();
        drawArcButton = new java.awt.Button();
        startingAngleTextField = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        extentAngleTextField = new java.awt.TextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        mainCanvas.setBackground(new java.awt.Color(0, 0, 0));
        mainCanvas.setName("mainCanvas"); // NOI18N

        drawArcButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        drawArcButton.setLabel("drawArcButton");
        drawArcButton.setName("drawArcButton"); // NOI18N
        drawArcButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DrawMouseEntered(evt);
            }
        });
        drawArcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrawActionPerformed(evt);
            }
        });

        startingAngleTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        startingAngleTextField.setName("startingAngleTextField"); // NOI18N

        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setName(""); // NOI18N
        label1.setText("Starting Angle");

        label2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label2.setName(""); // NOI18N
        label2.setText("Extent Angle");

        extentAngleTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        extentAngleTextField.setName("extentAngleTextField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(drawArcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(extentAngleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(startingAngleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(mainCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startingAngleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(extentAngleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(drawArcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void DrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrawActionPerformed
        // TODO add your handling code here:
        Graphics g = mainCanvas.getGraphics();
        g.setColor(Color.yellow);
        g.fillArc(150, 50, 150, 150, Integer.parseInt(startingAngleTextField.getText()), Integer.parseInt(extentAngleTextField.getText()));
//        Arc2D.Float arc = new Arc2D.Float(Arc2D.PIE);
//        arc.setFrame(150, 50, 150, 150);
//        arc.setAngleStart(Integer.parseInt(startingAngleTextField.getText()));
//        arc.setAngleExtent(Integer.parseInt(extentAngleTextField.getText()));
//        Graphics2D g2d = (Graphics2D) mainCanvas.getGraphics();
//        mainCanvas.getGraphics().drawAr
//        g2d.setColor(Color.yellow);
//        g2d.drawString("Fuck", 100, 100);
//        g2d.fill(arc);
//        g2d.setColor(Color.black);
//        g2d.draw(arc);
    }//GEN-LAST:event_DrawActionPerformed

    private void DrawMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DrawMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawingArcs().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button drawArcButton;
    private java.awt.Canvas mainCanvas;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.TextField startingAngleTextField;
    private java.awt.TextField extentAngleTextField;
    // End of variables declaration//GEN-END:variables
}
