package com.codechum.awt.DrawingShapes;

import java.awt.*;
import java.awt.event.MouseEvent;

public class DrawingInACanvas extends java.awt.Frame {

    /**
     * Creates new form CODECHUMACTIVITY
     */
    public DrawingInACanvas() {
        chkGrp = new CheckboxGroup();
        initComponents();
        setTitle("Drawing Shapes");
        redCheckBox.setName("redCheckBox");
        greenCheckBox.setName("greenCheckBox");
        blueCheckBox.setName("blueCheckBox");
    }
    
    public void drawOval(MouseEvent evt) {
        Color c;
        
        if (redCheckBox.getState()) {
            c = Color.red;
        } else if (greenCheckBox.getState()) {
            c = Color.green;
        } else {
            c = Color.blue;
        }
        
        Graphics g = mainCanvas.getGraphics();
 
        g.setColor(c);
 
        int x, y;
        x = evt.getX();
        y = evt.getY();
 
        g.fillOval(x, y, 15, 15);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainCanvas = new java.awt.Canvas();
        redCheckBox = new java.awt.Checkbox();
        greenCheckBox = new java.awt.Checkbox();
        blueCheckBox = new java.awt.Checkbox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        mainCanvas.setBackground(new java.awt.Color(204, 204, 204));
        mainCanvas.setForeground(new java.awt.Color(153, 153, 153));
        mainCanvas.setName("mainCanvas"); // NOI18N
        mainCanvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvas1MouseClicked(evt);
            }
        });
        mainCanvas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                canvas1MouseDragged(evt);
            }
        });

        redCheckBox.setCheckboxGroup(chkGrp);
        redCheckBox.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        redCheckBox.setLabel("Red");
        redCheckBox.setName("redCheckBox"); // NOI18N
        redCheckBox.setState(true);

        greenCheckBox.setCheckboxGroup(chkGrp);
        greenCheckBox.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        greenCheckBox.setLabel("Green");
        greenCheckBox.setName("chkGreen"); // NOI18N

        blueCheckBox.setCheckboxGroup(chkGrp);
        blueCheckBox.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        blueCheckBox.setLabel("Blue");
        blueCheckBox.setName("chkBlue"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(redCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(greenCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(blueCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(mainCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greenCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void canvas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvas1MouseClicked
        // TODO add your handling code here:
        drawOval(evt);
    }//GEN-LAST:event_canvas1MouseClicked

    private void canvas1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvas1MouseDragged
        // TODO add your handling code here:
        drawOval(evt);
    }//GEN-LAST:event_canvas1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawingInACanvas().setVisible(true);
            }
        });
    }

    private CheckboxGroup chkGrp;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas mainCanvas;
    private java.awt.Checkbox redCheckBox;
    private java.awt.Checkbox greenCheckBox;
    private java.awt.Checkbox blueCheckBox;
    // End of variables declaration//GEN-END:variables
}
