/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.codechum.awt.textField;

/**
 *
 * @author AzalithenPC
 */
public class CustomCharacterRemover extends java.awt.Frame {

    /**
     * Creates new form AWTTextField1
     */
    public CustomCharacterRemover() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        checkbox3 = new java.awt.Checkbox();
        button1 = new java.awt.Button();

        setTitle("Custom Character Remover");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textField1.setName("messageTextField"); // NOI18N
        add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 190, 100));

        checkbox1.setLabel("Vowels");
        checkbox1.setName("vowelCheckbox"); // NOI18N
        add(checkbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        checkbox2.setLabel("Consonants");
        checkbox2.setName("consonantCheckbox"); // NOI18N
        add(checkbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        checkbox3.setLabel("Numbers");
        checkbox3.setName("numberCheckbox"); // NOI18N
        add(checkbox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        button1.setLabel("Remove");
        button1.setName("removeButton"); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        if (checkbox1.getState()) {
            textField1.setText(textField1.getText().replaceAll("[AEIOUaeiou]", ""));
        }
        if (checkbox2.getState()) {
            textField1.setText(textField1.getText().replaceAll("[BCDFGHJKLMNPQRSTVWXYZbcdfghjklmnpqrstvwxyz]", ""));
        }
        if (checkbox3.getState()) {
            textField1.setText(textField1.getText().replaceAll("\\d", ""));
        }
        textField1.setText(textField1.getText().trim());
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomCharacterRemover().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox2;
    private java.awt.Checkbox checkbox3;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
