/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.codechum.awt.textField;

/**
 *
 * @author AzalithenPC
 */
public class StringConcatenator extends java.awt.Frame {

    /**
     * Creates new form AWTTextField2
     */
    public StringConcatenator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        label1 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        label2 = new java.awt.Label();
        button1 = new java.awt.Button();
        label3 = new java.awt.Label();

        setTitle("String Concatenator");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textField1.setName("textField1"); // NOI18N
        add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 180, 30));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setName("label1"); // NOI18N
        label1.setText("String 1");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        textField2.setName("textField2"); // NOI18N
        add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 180, 30));

        label2.setName("label2"); // NOI18N
        label2.setText("String 2");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        button1.setLabel("Concatenate");
        button1.setName("concatenateButton"); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(204, 255, 255));
        label3.setName("resultLabel"); // NOI18N
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 220, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        label3.setText(textField1.getText() + " " + textField2.getText());
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StringConcatenator().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
